package bindings

import (
	"bytes"
	"fmt"
	"go/format"
	"maps"
	"strings"
)

// Options controls one emission.
type Options struct {
	Package string
	// Constants are integer constants declared by other includes, by name.
	// The emitter needs them to fold `#define` bodies and enum initialisers
	// that refer across files; without them those declarations are refused.
	Constants map[string]int64
	// Names are the identifiers other includes emitted into the same Go
	// package, keyed by receiver type with "" for package scope. Emitting
	// several includes into one package needs them: two files declaring the
	// same name is a package that does not compile, and the second one has
	// to be refused rather than written.
	Names map[string]map[string]bool
}

// Emission is the result of rendering one include.
type Emission struct {
	Source   []byte
	Refusals []Refusal
	// Constants are the integer constants this file resolved, including the
	// ones passed in. Feed them to the includes that depend on this one.
	Constants map[string]int64
	// Names are the identifiers claimed so far, including the ones passed
	// in. Feed them to the next include emitted into the same package.
	Names map[string]map[string]bool
}

// Emit renders one parsed include as a Go source file. An error means the
// emitted text is not valid Go, which is a bug here rather than a bad input.
func Emit(f *File, opt Options) (Emission, error) {
	e := &emitter{
		file:   f,
		pkg:    opt.Package,
		taken:  make(map[string]map[string]bool, len(opt.Names)),
		consts: make(map[string]int64, len(opt.Constants)),
	}
	maps.Copy(e.consts, opt.Constants)
	for recv, names := range opt.Names {
		e.taken[recv] = maps.Clone(names)
	}
	e.run()
	out := Emission{Source: e.b.Bytes(), Refusals: e.refusals, Constants: e.consts, Names: e.taken}
	src, err := format.Source(e.b.Bytes())
	if err != nil {
		return out, fmt.Errorf("formatting emitted Go for %s: %w", f.Path, err)
	}
	out.Source = src
	return out, nil
}

type emitter struct {
	file     *File
	pkg      string
	b        bytes.Buffer
	refusals []Refusal
	taken    map[string]map[string]bool // receiver type -> member names already emitted
	consts   map[string]int64           // integer constants resolved so far
	mmNames  map[string]bool            // methodmaps declared by this file
}

func (e *emitter) refuse(pos Pos, kind, detail, reason string) {
	e.refusals = append(e.refusals, Refusal{Pos: pos, Kind: kind, Detail: truncate(detail), Reason: reason})
}

func (e *emitter) run() {
	e.mmNames = make(map[string]bool, len(e.file.Methodmaps))
	for _, mm := range e.file.Methodmaps {
		e.mmNames[mm.Name] = true
	}
	fmt.Fprintf(&e.b, "// Code generated by internal/bindings from %s. DO NOT EDIT.\n\n", e.file.Path)
	fmt.Fprintf(&e.b, "package %s\n\n", e.pkg)
	for _, en := range e.file.Enums {
		e.enum(en)
	}
	for _, es := range e.file.EnumStructs {
		e.enumStruct(es)
	}
	for _, td := range e.file.Typedefs {
		e.typedef(td)
	}
	for _, ts := range e.file.Typesets {
		e.typeset(ts)
	}
	for _, mm := range e.file.Methodmaps {
		e.methodmap(mm)
	}
	for _, d := range e.file.Defines {
		e.define(d)
	}
	for _, n := range e.file.Natives {
		e.native(n)
	}
	for _, n := range e.file.Stocks {
		e.native(n)
	}
}

func (e *emitter) doc(text string) {
	for line := range strings.SplitSeq(text, "\n") {
		if line == "" {
			e.b.WriteString("//\n")
			continue
		}
		fmt.Fprintf(&e.b, "// %s\n", line)
	}
}

func (e *emitter) native(n Native) {
	params, result, err := signature(n.Params, n.Return)
	if err != nil {
		e.refuse(n.Pos, "native", n.Name, err.Error())
		return
	}
	if !e.claim("", goIdent(n.Name), n.Pos) {
		return
	}
	e.doc(n.Doc)
	if note := defaultsNote(n.Params); note != "" {
		fmt.Fprintf(&e.b, "%s\n", note)
	}
	fmt.Fprintf(&e.b, "func %s(%s) %s { %s }\n\n", goIdent(n.Name), params, result, stub(n.Name))
}

func stub(name string) string {
	return fmt.Sprintf("panic(%q)", "bindings: "+name+" is SourcePawn and has no Go body")
}

// claim reserves a member name on a receiver type, refusing a second use
// rather than emitting Go that will not compile.
func (e *emitter) claim(recv, name string, pos Pos) bool {
	names, ok := e.taken[recv]
	if !ok {
		names = map[string]bool{}
		e.taken[recv] = names
	}
	if names[name] {
		where := "the package"
		if recv != "" {
			where = recv
		}
		e.refuse(pos, "declaration", recv+"."+name, "name already used on "+where)
		return false
	}
	names[name] = true
	return true
}

func (e *emitter) methodmap(mm Methodmap) {
	name := goIdent(mm.Name)
	if !e.claim("", name, mm.Pos) {
		return
	}
	e.doc(mm.Doc)
	if mm.Parent == "" {
		fmt.Fprintf(&e.b, "type %s struct{ Ref int32 }\n\n", name)
	} else {
		fmt.Fprintf(&e.b, "type %s struct{ %s }\n\n", name, goIdent(mm.Parent))
	}
	for _, m := range mm.Methods {
		e.method(name, m)
	}
	for _, p := range mm.Properties {
		e.property(name, p)
	}
}

// The receiver is named `this`, which is what SourcePawn calls it inside a
// methodmap and therefore a name no parameter in the tree can carry. A
// shorter receiver collides: nav.inc has a method whose parameter is `x`.
func (e *emitter) method(recv string, m Method) {
	params, result, err := signature(m.Params, m.Return)
	if err != nil {
		e.refuse(m.Pos, "method", recv+"."+m.Name, err.Error())
		return
	}
	name := goIdent(m.Name)
	switch m.Kind {
	case MethodConstructor:
		name = "New" + recv
		if !e.claim("", name, m.Pos) {
			return
		}
		e.doc(m.Doc)
		fmt.Fprintf(&e.b, "func %s(%s) %s { %s }\n\n", name, params, recv, stub(recv+"()"))
		return
	case MethodStatic:
		name = recv + "_" + name
		if !e.claim("", name, m.Pos) {
			return
		}
		e.doc(m.Doc)
		fmt.Fprintf(&e.b, "func %s(%s) %s { %s }\n\n", name, params, result, stub(recv+"."+m.Name))
		return
	case MethodPlain:
	}
	if !e.claim(recv, name, m.Pos) {
		return
	}
	e.doc(m.Doc)
	if note := defaultsNote(m.Params); note != "" {
		fmt.Fprintf(&e.b, "%s\n", note)
	}
	fmt.Fprintf(&e.b, "func (this %s) %s(%s) %s { %s }\n\n", recv, name, params, result, stub(recv+"."+m.Name))
}

func (e *emitter) property(recv string, p Property) {
	typ, err := goType(p.Type)
	if err != nil || typ == "" {
		e.refuse(p.Pos, "property", recv+"."+p.Name, "unrepresentable property type")
		return
	}
	name := goIdent(p.Name)
	if p.Get && e.claim(recv, name, p.Pos) {
		e.doc(p.Doc)
		fmt.Fprintf(&e.b, "func (this %s) %s() %s { %s }\n\n", recv, name, typ, stub(recv+"."+p.Name))
	}
	setter := "Set" + strings.ToUpper(p.Name[:1]) + p.Name[1:]
	if p.Set && e.claim(recv, setter, p.Pos) {
		fmt.Fprintf(&e.b, "func (this %s) %s(v %s) { %s }\n\n", recv, setter, typ, stub(recv+"."+p.Name+" set"))
	}
}

func (e *emitter) typedef(td Typedef) {
	params, result, err := signature(td.Params, td.Return)
	if err != nil {
		e.refuse(td.Pos, "typedef", td.Name, err.Error())
		return
	}
	if !e.claim("", goIdent(td.Name), td.Pos) {
		return
	}
	e.doc(td.Doc)
	fmt.Fprintf(&e.b, "type %s func(%s) %s\n\n", goIdent(td.Name), params, result)
}

func (e *emitter) enumStruct(es EnumStruct) {
	name := goIdent(es.Name)
	if !e.claim("", name, es.Pos) {
		return
	}
	e.doc(es.Doc)
	fmt.Fprintf(&e.b, "type %s struct {\n", name)
	for _, f := range es.Fields {
		typ, err := goType(f.Type)
		if err != nil || typ == "" {
			e.refuse(f.Pos, "enum struct field", name+"."+f.Name, "unrepresentable field type")
			continue
		}
		fmt.Fprintf(&e.b, "\t%s %s\n", goIdent(f.Name), typ)
	}
	e.b.WriteString("}\n\n")
	for _, m := range es.Methods {
		e.method(name, m)
	}
}
