// Package bindgen drives internal/bindings over a whole include tree and
// writes one Go package.
//
// internal/bindings reads one include at a time, which is the right unit for
// a parser and the wrong unit for an output: tf2utils.inc names TFCond,
// TFClassType and Address, and every one of them is declared somewhere else.
// Resolving those edges is this package's job. It orders the tree so a file
// is emitted after the files it includes, threads the constants and the
// claimed names of each file into the next, and declares the handful of tags
// the SourcePawn compiler supplies that no include in the tree writes down.
//
// The output is one Go package, not one per include. SourcePawn's include
// graph is not a DAG of packages: core.inc, handles.inc and functions.inc
// refer to each other, and Go forbids an import cycle. One package is the
// only shape that survives that, and it costs nothing, because a binding is
// a declaration with no body and nothing to hide behind a package boundary.
package bindgen

import (
	"fmt"
	"maps"
	"path/filepath"
	"slices"
	"strings"

	"github.com/m-this/tf2-mvm-bots-go/internal/bindings"
)

// Options controls one generation run.
type Options struct {
	// Root is the include tree, the directory holding the .inc files.
	Root string
	// Package is the name of the Go package written.
	Package string
}

// Result is a generated package: one Go file per include, plus the file
// declaring the tags no include declares, plus everything the run turned
// down.
type Result struct {
	// Files maps a file name inside the package directory to its source.
	Files map[string][]byte
	// Order is the order the includes were emitted in, tree-relative.
	Order []string
	// Names are the identifiers the package declares, keyed by receiver type
	// with "" for package scope.
	Names map[string]map[string]bool
	// BuiltinTags are the tag names no include in the tree declares. They are
	// emitted as plain cell types, and the list is short on purpose: a long
	// one means a declaration was refused, not that SourcePawn grew a tag.
	BuiltinTags []string
	// Refusals are every declaration the parser or the emitter turned down.
	Refusals []bindings.Refusal
}

// builtinsFile is the name of the generated file holding the undeclared tags.
const builtinsFile = "zz_builtin_tags.go"

// Generate parses the whole tree and renders it as one Go package. An error
// means a file could not be read or the emitter produced text that is not Go,
// which is a bug here rather than a bad include.
func Generate(opt Options) (*Result, error) {
	if opt.Package == "" {
		return nil, fmt.Errorf("bindgen: no package name")
	}
	paths, err := includeFiles(opt.Root)
	if err != nil {
		return nil, err
	}
	parsed := make(map[string]*bindings.File, len(paths))
	for _, rel := range paths {
		f, err := bindings.ParseFile(filepath.Join(opt.Root, rel))
		if err != nil {
			return nil, err
		}
		f.Path = rel
		parsed[rel] = f
	}
	order, err := includeOrder(opt.Root, paths)
	if err != nil {
		return nil, err
	}

	res := &Result{
		Files:       make(map[string][]byte, len(order)+1),
		Order:       order,
		Names:       map[string]map[string]bool{},
		BuiltinTags: undeclaredTags(parsed, order),
	}
	res.Files[builtinsFile] = builtinTagsSource(opt.Package, res.BuiltinTags)
	names := map[string]map[string]bool{"": {}}
	for _, tag := range res.BuiltinTags {
		names[""][tag] = true
	}
	consts := map[string]int64{}
	for _, rel := range order {
		f := parsed[rel]
		res.Refusals = append(res.Refusals, f.Refusals...)
		out, err := bindings.Emit(f, bindings.Options{
			Package: opt.Package, Constants: consts, Names: names,
		})
		if err != nil {
			return nil, fmt.Errorf("bindgen: %w", err)
		}
		consts = out.Constants
		names = out.Names
		res.Refusals = append(res.Refusals, out.Refusals...)
		res.Files[goFileName(rel)] = out.Source
	}
	res.Names = names
	return res, nil
}

// goFileName flattens a tree-relative include path into one file name, so two
// includes with the same base name land in the same package without
// colliding and a reader can still see which include a file came from.
func goFileName(rel string) string {
	name := strings.TrimSuffix(filepath.ToSlash(rel), ".inc")
	name = strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(name)
	return name + ".go"
}

// builtinTagsSource renders the tags no include declares. They are cells, and
// nothing in the tree hangs a member off them, so a defined type over int32
// is the whole truth about them.
func builtinTagsSource(pkg string, tags []string) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by internal/bindgen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("// These tags are named by declarations in the include tree and declared\n")
	b.WriteString("// by none of them: the SourcePawn compiler supplies them. Each is a cell.\n\n")
	for _, tag := range tags {
		fmt.Fprintf(&b, "type %s int32\n\n", tag)
	}
	return []byte(b.String())
}

// RefusalsByReason groups the run's refusals the way Coverage does, so a
// caller reports kinds rather than a wall of lines.
func (r *Result) RefusalsByReason() map[string]int {
	byReason := make(map[string]int, len(r.Refusals))
	for _, ref := range r.Refusals {
		byReason[ref.Kind+": "+ref.Reason]++
	}
	return byReason
}

// Declared reports whether the package declares name, at package scope or as
// a member of any type.
func (r *Result) Declared(name string) bool {
	for _, names := range r.Names {
		if names[name] {
			return true
		}
	}
	return false
}

// declaredMember reports whether the package offers a way to reach the
// SourcePawn member `x.name`. A property becomes a getter under its own name
// and a setter under Set-name, and a static method loses its receiver and
// becomes a package function named Type_name, so all three spellings count.
func (r *Result) declaredMember(name string) bool {
	if r.Declared(name) || r.Declared("Set"+strings.ToUpper(name[:1])+name[1:]) {
		return true
	}
	suffix := "_" + name
	for pkgName := range r.Names[""] {
		if strings.HasSuffix(pkgName, suffix) {
			return true
		}
	}
	return false
}

// PackageScope lists the identifiers the package declares at top level.
func (r *Result) PackageScope() []string {
	return slices.Sorted(maps.Keys(r.Names[""]))
}
