package spgen

import (
	"fmt"
	"strconv"
	"strings"
)

// Data emits the file the plugin includes and the differential test compiles:
// the three enums the edge exchanges with the plugin, then the decision graph
// as three parallel arrays of nodes and one array of roots indexed by the
// axes. It declares no function and calls nothing.
func Data(cfg Config, t Table) (string, error) {
	head, err := enums(cfg)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	p := cfg.Prefix

	b.WriteString(header(cfg))
	b.WriteString(head)

	b.WriteString("/* The decision as data, so the edge can ask lazily\n")
	b.WriteString(" *\n")
	b.WriteString(" * Three of the predicates have side effects, so filling them all in\n")
	b.WriteString(" * before deciding is not what the plugin does today. A node names one\n")
	b.WriteString(" * predicate and the node to go to for each answer; the edge asks for a\n")
	b.WriteString(" * predicate only when the walk reaches it, and never twice, because the\n")
	b.WriteString(" * answer is what chose the next node.\n")
	b.WriteString(" *\n")
	b.WriteString(" * A node with " + p + "NodePredicate of -1 answers: " + p + "NodeWhenTrue\n")
	b.WriteString(" * holds the outcome.\n")
	b.WriteString(" */\n")

	fmt.Fprintf(&b, "#define %sPredicateCount %d\n\n", p, len(t.Predicates))
	b.WriteString("enum\n{\n")
	for i, name := range t.Predicates {
		comma := ","
		if i == len(t.Predicates)-1 {
			comma = ""
		}
		fmt.Fprintf(&b, "\t%sPred%s = %d%s\n", p, name, i, comma)
	}
	b.WriteString("};\n\n")

	fmt.Fprintf(&b, "#define %sNodeCount %d\n\n", p, len(t.Predicate))
	writeCells(&b, p+"NodePredicate", p+"NodeCount", t.Predicate)
	writeCells(&b, p+"NodeWhenTrue", p+"NodeCount", t.WhenTrue)
	writeCells(&b, p+"NodeWhenFalse", p+"NodeCount", t.WhenFalse)

	dims := ""
	for _, a := range t.Axes {
		dims += "[" + strconv.Itoa(a.Size) + "]"
	}
	fmt.Fprintf(&b, "int %sRoot%s = %s;\n", p, dims, nested(t.Roots, sizes(t.Axes), 0))
	return b.String(), nil
}

// header is what a reader of the plugin sees first: where the file came from,
// and that a table produced by running the decision cannot disagree with it.
func header(cfg Config) string {
	return "/* Generated by internal/spgen. Do not edit.\n" +
		" *\n" +
		" * The decision in internal/actionsel, as data.\n" +
		" *\n" +
		" * The table is not a translation of the Go. It is extracted by running\n" +
		" * actionsel.Select against a Facts that refuses a question it has not\n" +
		" * been told about, answering each refused question both ways and\n" +
		" * recurring, so the order the table asks in is the order the Go\n" +
		" * evaluates in, short circuits included.\n" +
		" *\n" +
		" * Nothing here calls anything. The edge in " + cfg.Guard + "_dispatch.sp answers\n" +
		" * the predicates and maps an outcome back onto the action it hands the bot.\n" +
		" */\n" +
		"#if defined _" + cfg.Guard + "_included\n" +
		" #endinput\n" +
		"#endif\n" +
		"#define _" + cfg.Guard + "_included\n" +
		"\n" +
		"#pragma semicolon 1\n" +
		"#pragma newdecls required\n" +
		"\n"
}

func sizes(axes []Axis) []int {
	out := make([]int, 0, len(axes))
	for _, a := range axes {
		out = append(out, a.Size)
	}
	return out
}

// nested writes a row-major slice as the nested braces SourcePawn wants.
func nested(cells []int32, dims []int, depth int) string {
	if len(dims) == 1 {
		parts := make([]string, 0, len(cells))
		for _, c := range cells {
			parts = append(parts, strconv.Itoa(int(c)))
		}
		return "{" + strings.Join(parts, ", ") + "}"
	}
	stride := 1
	for _, d := range dims[1:] {
		stride *= d
	}
	pad := strings.Repeat("\t", depth+1)
	parts := make([]string, 0, dims[0])
	for i := range dims[0] {
		parts = append(parts, pad+nested(cells[i*stride:(i+1)*stride], dims[1:], depth+1))
	}
	return "{\n" + strings.Join(parts, ",\n") + "\n" + strings.Repeat("\t", depth) + "}"
}

// writeCells wraps at eight per line, which keeps a table of a few hundred
// nodes readable in a diff.
func writeCells(b *strings.Builder, name, count string, cells []int32) {
	fmt.Fprintf(b, "int %s[%s] = {\n", name, count)
	for i := 0; i < len(cells); i += 8 {
		end := min(i+8, len(cells))
		parts := make([]string, 0, 8)
		for _, c := range cells[i:end] {
			parts = append(parts, strconv.Itoa(int(c)))
		}
		line := "\t" + strings.Join(parts, ", ")
		if end < len(cells) {
			line += ","
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("};\n\n")
}
