package spgen

import (
	"fmt"
	"strings"
)

// Dispatch emits the plugin's edge: the one function that answers a predicate,
// the loop that walks the table, and the switch that turns an outcome id back
// into the SuspendFor call it came from.
//
// This is the only generated file that calls into the engine, and it is
// generated for the same reason everything else here is: the pairing of an id
// with a behaviour and a reason string is one fact, and a hand-written copy of
// it would be a second.
func Dispatch(cfg Config, preds []Predicate, outcomes []Outcome, source string) string {
	var b strings.Builder
	p := cfg.Prefix

	b.WriteString("/* Generated by internal/spgen. Do not edit.\n")
	b.WriteString(" *\n")
	b.WriteString(" * The edge between the plugin and the generated decision, from " + source + ".\n")
	b.WriteString(" * Include it after " + cfg.Guard + ".sp, inside the plugin, where the\n")
	b.WriteString(" * behaviours and the predicates are in scope.\n")
	b.WriteString(" *\n")
	b.WriteString(" * " + p + "GetDesiredBotAction replaces the body of GetDesiredBotAction.\n")
	b.WriteString(" * The RecoverDefenderFromDisconnectedSpawn call at the top of the shipped\n")
	b.WriteString(" * function is not part of the decision and stays in the caller.\n")
	b.WriteString(" */\n")
	b.WriteString("#if !defined _" + cfg.Guard + "_included\n")
	b.WriteString(" #error Include " + cfg.Guard + ".sp before this file.\n")
	b.WriteString("#endif\n\n")
	b.WriteString("#pragma semicolon 1\n")
	b.WriteString("#pragma newdecls required\n\n")

	b.WriteString("/* One predicate, asked once, only when the walk reaches it. */\n")
	fmt.Fprintf(&b, "static bool %sAsk(int client, int predicate)\n{\n\tswitch (predicate)\n\t{\n", p)
	for _, pr := range preds {
		fmt.Fprintf(&b, "\t\tcase %sPred%s:\n\t\t{\n\t\t\treturn %s;\n\t\t}\n", p, pr.Field, pr.Call)
	}
	b.WriteString("\t}\n\n\treturn false;\n}\n\n")

	b.WriteString("/* The walk. The bound is the predicate count, so it cannot spin. */\n")
	fmt.Fprintf(&b, "stock %sAction %sWalk(int client, %sRoundState state, %sClass botClass)\n{\n", p, p, p, p)
	fmt.Fprintf(&b, "\tint node = %sRoot[view_as<int>(state)][view_as<int>(botClass)];\n\n", p)
	fmt.Fprintf(&b, "\tfor (int step = 0; step <= %sPredicateCount; step++)\n\t{\n", p)
	fmt.Fprintf(&b, "\t\tif (%sNodePredicate[node] == -1)\n\t\t\treturn view_as<%sAction>(%sNodeWhenTrue[node]);\n\n", p, p, p)
	fmt.Fprintf(&b, "\t\tif (%sAsk(client, %sNodePredicate[node]))\n\t\t\tnode = %sNodeWhenTrue[node];\n", p, p, p)
	fmt.Fprintf(&b, "\t\telse\n\t\t\tnode = %sNodeWhenFalse[node];\n\t}\n\n", p)
	fmt.Fprintf(&b, "\treturn %sActionNone;\n}\n\n", p)

	b.WriteString("/* One outcome id, one call site of the function this replaces. The\n")
	b.WriteString(" * reason strings are the shipped ones byte for byte: they reach the debug\n")
	b.WriteString(" * output and the test-bed's telemetry, so renaming one is a change. */\n")
	fmt.Fprintf(&b, "stock Action %sDispatch(int client, BehaviorAction action, %sAction outcome)\n{\n\tswitch (outcome)\n\t{\n", p, p)
	for _, o := range outcomes {
		if o.Behaviour == "" {
			continue
		}
		fmt.Fprintf(&b, "\t\tcase %s%s:\n\t\t{\n", p, o.Const)
		if o.Effect != "" {
			fmt.Fprintf(&b, "\t\t\t%s\n", o.Effect)
		}
		fmt.Fprintf(&b, "\t\t\treturn action.SuspendFor(%s(), %q);\n\t\t}\n", o.Behaviour, o.Reason)
	}
	b.WriteString("\t}\n\n")
	b.WriteString("\t/* Every other outcome is the shipped Plugin_Continue:\n")
	for _, o := range outcomes {
		if o.Behaviour == "" {
			fmt.Fprintf(&b, "\t * %s%s: %s\n", p, o.Const, o.Note)
		}
	}
	b.WriteString("\t */\n\treturn Plugin_Continue;\n}\n\n")

	b.WriteString("/* The whole of GetDesiredBotAction's decision. */\n")
	fmt.Fprintf(&b, "stock Action %sGetDesiredBotAction(int client, BehaviorAction action)\n{\n", p)
	fmt.Fprintf(&b, "\t%sRoundState state = view_as<%sRoundState>(GameRules_GetRoundState());\n", p, p)
	fmt.Fprintf(&b, "\t%sClass botClass = view_as<%sClass>(TF2_GetPlayerClass(client));\n\n", p, p)
	fmt.Fprintf(&b, "\treturn %sDispatch(client, action, %sWalk(client, state, botClass));\n}\n", p, p)
	return b.String()
}
