package spgen

import (
	"fmt"
	"go/ast"
	"go/constant"
	"go/token"
	"go/types"
	"strings"
)

type generator struct {
	fset *token.FileSet
	info *types.Info
	pkg  *types.Package
	cfg  Config

	b   strings.Builder
	err error
}

// refuse records the first construct with no translation. Generation carries
// on so the caller gets a position rather than a half-written file, and the
// output is thrown away.
func (g *generator) refuse(pos token.Pos, construct, fix string) {
	if g.err == nil {
		g.err = Unsupported{Pos: g.fset.Position(pos), Construct: construct, Fix: fix}
	}
}

func (g *generator) emit(files []*ast.File, names []string) (string, error) {
	g.header(names)
	// SourcePawn reads a file once: a tag has to be declared before it is
	// used, so the constants come out before the enum structs and both come
	// out before the functions. Function order does not matter, spcomp
	// resolves a call to a function defined further down.
	g.eachDecl(files, func(d ast.Decl) bool { gd, ok := d.(*ast.GenDecl); return ok && gd.Tok == token.CONST })
	g.eachDecl(files, func(d ast.Decl) bool { gd, ok := d.(*ast.GenDecl); return ok && gd.Tok == token.TYPE })
	g.eachDecl(files, func(d ast.Decl) bool {
		gd, ok := d.(*ast.GenDecl)
		return ok && gd.Tok != token.CONST && gd.Tok != token.TYPE
	})
	g.eachDecl(files, func(d ast.Decl) bool { _, ok := d.(*ast.FuncDecl); return ok })
	if g.err != nil {
		return "", g.err
	}
	return g.b.String(), nil
}

func (g *generator) eachDecl(files []*ast.File, want func(ast.Decl) bool) {
	for _, f := range files {
		for _, d := range f.Decls {
			if want(d) {
				g.decl(d)
			}
		}
	}
}

func (g *generator) header(names []string) {
	g.line("/* Generated by internal/spgen. Do not edit.")
	g.line(" *")
	g.line(" * The source is the Go in internal/actionsel:")
	for _, n := range names {
		g.line(" *   internal/actionsel/" + n)
	}
	g.line(" *")
	g.line(" * Every function here is pure: plain values in, a plain value out, no")
	g.line(" * native called and no state owned. The hand-written SourcePawn fills the")
	g.line(" * inputs and maps the returned id onto the action it hands the bot.")
	g.line(" */")
	guard := "_" + g.cfg.Guard + "_included"
	g.line("#if defined " + guard)
	g.line(" #endinput")
	g.line("#endif")
	g.line("#define " + guard)
	g.line("")
	g.line("#pragma semicolon 1")
	g.line("#pragma newdecls required")
	g.line("")
}

func (g *generator) decl(d ast.Decl) {
	switch n := d.(type) {
	case *ast.GenDecl:
		g.genDecl(n)
	case *ast.FuncDecl:
		g.funcDecl(n)
	}
}

func (g *generator) genDecl(d *ast.GenDecl) {
	switch d.Tok {
	case token.IMPORT:
		if len(d.Specs) > 0 {
			g.refuse(d.Pos(), "an import",
				"spgen translates one self-contained package; move what the import gave you into this package or into the hand-written SourcePawn")
		}
	case token.TYPE:
		for _, s := range d.Specs {
			g.typeSpec(s.(*ast.TypeSpec))
		}
	case token.CONST:
		g.constDecl(d)
	case token.VAR:
		g.refuse(d.Pos(), "a package-level variable",
			"a generated body owns no state; pass the value in")
	}
}

// typeSpec emits a struct as an enum struct. A named type over a basic type is
// emitted by its constant block instead, because a SourcePawn enum is where
// the name and the values live together.
func (g *generator) typeSpec(s *ast.TypeSpec) {
	st, isStruct := s.Type.(*ast.StructType)
	if !isStruct {
		return
	}
	g.line("enum struct " + g.name(s.Name.Name))
	g.line("{")
	for _, f := range st.Fields.List {
		for _, n := range f.Names {
			g.line("\t" + g.declare(g.info.TypeOf(f.Type), n.Name, f.Type.Pos()) + ";")
		}
	}
	g.line("}")
	g.line("")
}

// constDecl emits one const block as one SourcePawn enum. A block whose
// constants share a named type takes that type's name, so the parameters that
// are declared with it type-check; an untyped block becomes an anonymous enum.
func (g *generator) constDecl(d *ast.GenDecl) {
	type entry struct {
		name string
		val  string
	}
	var entries []entry
	tag := ""
	for _, spec := range d.Specs {
		vs := spec.(*ast.ValueSpec)
		for _, n := range vs.Names {
			if n.Name == "_" {
				g.refuse(n.Pos(), "a blank constant",
					"name it; the generated enum has one entry per constant")
				continue
			}
			obj, ok := g.info.Defs[n].(*types.Const)
			if !ok {
				g.refuse(n.Pos(), "a constant with no value the type checker could compute",
					"write a literal, iota, or arithmetic over named constants")
				continue
			}
			if named, isNamed := obj.Type().(*types.Named); isNamed {
				tag = g.name(named.Obj().Name())
			}
			entries = append(entries, entry{g.name(n.Name), g.constValue(obj, n.Pos())})
		}
	}
	if len(entries) == 0 {
		return
	}
	g.line(strings.TrimRight("enum "+tag, " "))
	g.line("{")
	for i, e := range entries {
		comma := ","
		if i == len(entries)-1 {
			comma = ""
		}
		g.line("\t" + e.name + " = " + e.val + comma)
	}
	g.line("};")
	g.line("")
}

func (g *generator) constValue(obj *types.Const, pos token.Pos) string {
	v := obj.Val()
	switch v.Kind() {
	case constant.Int:
		s := v.ExactString()
		if _, ok := constant.Int64Val(v); !ok {
			g.refuse(pos, "a constant that does not fit a 32-bit cell", "narrow it to int32")
		}
		return s
	case constant.Bool:
		return v.ExactString()
	case constant.Float:
		f, _ := constant.Float64Val(v)
		return floatLiteral(f)
	default:
		g.refuse(pos, "a constant that is neither an integer, a float nor a bool",
			"the subset has no strings; use an int32 identifier")
		return "0"
	}
}

func floatLiteral(f float64) string {
	s := fmt.Sprintf("%g", f)
	if !strings.ContainsAny(s, ".e") {
		s += ".0"
	}
	return s
}

func (g *generator) funcDecl(d *ast.FuncDecl) {
	if d.Body == nil {
		g.refuse(d.Pos(), "a function with no body", "give it one, or leave it to the hand-written side")
		return
	}
	ret := "void"
	if d.Type.Results != nil {
		if len(d.Type.Results.List) != 1 || len(d.Type.Results.List[0].Names) > 1 {
			g.refuse(d.Type.Results.Pos(), "a function with more than one result",
				"return one value; several results become by-reference parameters, which spgen does not emit yet")
			return
		}
		ret = g.spType(g.info.TypeOf(d.Type.Results.List[0].Type), d.Type.Results.List[0].Type.Pos())
	}

	var params []string
	if d.Type.Params != nil {
		for _, f := range d.Type.Params.List {
			for _, n := range f.Names {
				params = append(params, g.declare(g.info.TypeOf(f.Type), identifier(n.Name), f.Type.Pos()))
			}
		}
	}

	g.line("stock " + ret + " " + g.name(d.Name.Name) + "(" + strings.Join(params, ", ") + ")")
	g.block(d.Body, 0)
	g.line("")
}

func (g *generator) line(s string) {
	g.b.WriteString(s)
	g.b.WriteByte('\n')
}

func (g *generator) indent(depth int, s string) {
	g.line(strings.Repeat("\t", depth) + s)
}
