/* Generated by internal/spbody from the Go it is named after. Do not edit. */

AreasCollector Go_kept;

// Search walks the ground near a point and returns the first area that is not a
// spawn room, leaving through three different returns on the way.
stock void Go_Search(float origin[3], int actor, float found[3])
{
	for (int i = 0; i < 3; i++)
	{
		found[i] = 0.0;
	}
	AreasCollector areas = TheNavMesh.CollectAreasInRadius(origin, 300.0);
	for (int i = 0; i < areas.Count(); i++)
	{
		CTFNavArea area = areas.Get(i);
		if (area.HasAttributeTF(RED_SPAWN_ROOM))
		{
			continue;
		}
		if (area.HasAttributeTF(BLUE_SPAWN_ROOM))
		{
			delete areas;
			return;
		}
		float centre[3];
		area.GetCenter(centre);
		if (IsPathToVectorPossible(actor, centre))
		{
			found = centre;
			delete areas;
			return;
		}
	}
	delete areas;
	return;
}

// Missing falls off the end, which is a way out too.
stock int Go_Missing(float origin[3])
{
	AreasCollector areas = TheNavMesh.CollectAreasInRadius(origin, 100.0);
	int count = areas.Count();
	delete areas;
	return count;
}

// Reload closes by hand rather than by defer, which is the shape that crashed.
//
// A closed handle keeps the number it had, and SourceMod hands that number out
// again. The variable then reads as neither null nor its own, so the guard that
// asks whether it is null lets the next call through and the call throws. delete
// is SourcePawn's close that writes null over the variable, so the golden pins
// that a close written by hand comes out as delete and not as a call to Close.
stock int Go_Reload(float origin[3])
{
	delete Go_kept;
	Go_kept = TheNavMesh.CollectAreasInRadius(origin, 100.0);
	return Go_kept.Count();
}

