/* Generated by internal/spbody from the Go it is named after. Do not edit. */

stock void Go_Search(float origin[3], int actor, float found[3])
{
	for (int i = 0; i < 3; i++)
	{
		found[i] = 0.0;
	}
	AreasCollector areas = TheNavMesh.CollectAreasInRadius(origin, 300.0);
	for (int i = 0; i < areas.Count(); i++)
	{
		CTFNavArea area = areas.Get(i);
		if (area.HasAttributeTF(RED_SPAWN_ROOM))
		{
			continue;
		}
		if (area.HasAttributeTF(BLUE_SPAWN_ROOM))
		{
			delete areas;
			return;
		}
		float centre[3];
		area.GetCenter(centre);
		if (IsPathToVectorPossible(actor, centre))
		{
			found = centre;
			delete areas;
			return;
		}
	}
	delete areas;
	return;
}

stock int Go_Missing(float origin[3])
{
	AreasCollector areas = TheNavMesh.CollectAreasInRadius(origin, 100.0);
	int count = areas.Count();
	delete areas;
	return count;
}

