/* Generated by internal/spbody from the Go it is named after. Do not edit. */

stock int Go_max_int(int a, int b)
{
	if (a > b)
	{
		return a;
	}
	return b;
}

stock int Go_min_int(int a, int b)
{
	if (a < b)
	{
		return a;
	}
	return b;
}

enum Go_Priority
{
	Go_PriorityIdle = 0,
	Go_PriorityBusy = 1,
	Go_PriorityUrgent = 2
};

#define Go_Slots (4)

enum struct Go_Sample
{
	int Client;
	float Score;
	int Recent[4];
}

int Go_seen[4] = {1, 2};
Go_Priority Go_worst = Go_PriorityIdle;

// Note records a client and returns what the highest priority seen so far is,
// which is the read-and-write a state emission has to get right.
stock Go_Priority Go_Note(int slot, Go_Priority p)
{
	Go_seen[slot]++;
	if (p > Go_worst)
	{
		Go_worst = p;
	}
	return Go_worst;
}

// Rank folds the sample into a priority, and shows the switch, the tagged
// return and the float comparison in one place.
stock Go_Priority Go_Rank(Go_Sample s, float threshold)
{
	// Off the scale is urgent, whoever it is.
	if (s.Score > threshold)
	{
		return Go_PriorityUrgent;
	}
	switch (s.Client)
	{
		case 0:
		{
			return Go_PriorityIdle;
		}
		case 1, 2:
		{
			return Go_PriorityBusy;
		}
	}
	return Go_PriorityIdle;
}

// SumRecent shows the range loop, the array index and the conversion the
// generator has to spell as a call.
stock int Go_SumRecent(Go_Sample s, float &average)
{
	int total;
	average = 0.0;
	total = 0;
	for (int i = 0; i < 4; i++)
	{
		total += s.Recent[i];
	}
	average = float(total) / 4.0;
	return total;
}

// Centre is the vector shape: SourcePawn returns a cell, so an array result
// becomes the parameter the caller supplies and this fills.
stock void Go_Centre(Go_Sample s, float centre[3])
{
	for (int i = 0; i < 3; i++)
	{
		centre[i] = 0.0;
	}
	centre[0] = s.Score;
	centre[1] = float(s.Client);
	centre[2] = 0.0;
	return;
}

// Offset shows the call site: a declaration and a call, never an expression.
stock float Go_Offset(Go_Sample s)
{
	float centre[3];
	Go_Centre(s, centre);
	return centre[0] + centre[1];
}

// Clamp shows min and max, the local declaration with no initialiser, and the
// defaults the SourcePawn callers of the ported functions rely on.
stock int Go_Clamp(int v, int low = 0, int high = 100)
{
	int out;
	out = Go_min_int(Go_max_int(v, low), high);
	return out;
}

// Middle is the other vector shape: SourcePawn returns the array, which is what
// util.sp's WorldSpaceCenter does and what its callers use inline.
stock float[] Go_Middle(Go_Sample s)
{
	float middle[3];
	middle[0] = s.Score;
	middle[1] = 0.0;
	middle[2] = float(s.Client);
	return middle;
}

// Reach shows the call site: assigned, never used to initialise, because spcomp
// takes one and not the other.
stock float Go_Reach(Go_Sample s)
{
	float middle[3];
	middle = Go_Middle(s);
	return middle[0] + middle[2];
}

