/* Generated by internal/spbody from the Go it is named after. Do not edit. */

stock int Go_max_int(int a, int b)
{
	if (a > b)
	{
		return a;
	}
	return b;
}

stock int Go_min_int(int a, int b)
{
	if (a < b)
	{
		return a;
	}
	return b;
}

enum Go_Priority
{
	Go_PriorityIdle = 0,
	Go_PriorityBusy = 1,
	Go_PriorityUrgent = 2
};

#define Go_Slots (4)

enum struct Go_Sample
{
	int Client;
	float Score;
	int Recent[4];
}

stock Go_Priority Go_Rank(Go_Sample s, float threshold)
{
	if (s.Score > threshold)
	{
		return Go_PriorityUrgent;
	}
	switch (s.Client)
	{
		case 0:
		{
			return Go_PriorityIdle;
		}
		case 1, 2:
		{
			return Go_PriorityBusy;
		}
	}
	return Go_PriorityIdle;
}

stock int Go_SumRecent(Go_Sample s, float &average)
{
	int total;
	total = 0;
	for (int i = 0; i < 4; i++)
	{
		total += s.Recent[i];
	}
	average = float(total) / 4.0;
	return total;
}

stock int Go_Clamp(int v, int low, int high)
{
	int out;
	out = Go_min_int(Go_max_int(v, low), high);
	return out;
}

