/* Generated by internal/spbody from the Go it is named after. Do not edit. */

stock void Go_Report(int actor, float spot[3])
{
	if (!redbots_manager_debug_actions.BoolValue)
	{
		return;
	}
	PrintToServer("ConfiguredDispenserSpot: %N takes the named spot %.0f %.0f %.0f", actor, spot[0], spot[1], spot[2]);
}

stock void Go_Quiet()
{
	PrintToServer("CTFBotMvMEngineerIdle_Update: RELOCATE NEST");
}

stock void Go_Stack(int client)
{
	char stack[512];
	ActionStackOf(client, stack, 512);
	PrintToServer("[defenderbots] %N is running %s", client, stack);
}

