/* Generated by internal/spbody from the Go it is named after. Do not edit. */

// Report is the running commentary a behaviour writes when the debug switch is
// on, which is also the property read.
stock void Go_Report(int actor, float spot[3])
{
	if (!redbots_manager_debug_actions.BoolValue)
	{
		return;
	}
	PrintToServer("ConfiguredDispenserSpot: %N takes the named spot %.0f %.0f %.0f", actor, spot[0], spot[1], spot[2]);
}

// Quiet takes no arguments at all, which is most of them.
stock void Go_Quiet()
{
	PrintToServer("CTFBotMvMEngineerIdle_Update: RELOCATE NEST");
}

// Stack fills a text buffer, which SourceMod declares with its length after it.
stock void Go_Stack(int client)
{
	char stack[512];
	ActionStackOf(client, stack, 512);
	PrintToServer("[defenderbots] %N is running %s", client, stack);
}

// Currency is the classname test the money and health and ammo searches all
// make: fill a buffer, then ask what it starts with.
stock bool Go_Currency(int entity)
{
	char class[512];
	GetEntityClassname(entity, class, 512);
	return StrContains(class, "item_currency", false) != -1;
}

