/* Generated by internal/spgen. Do not edit.
 *
 * The edge between the plugin and the generated decision, from internal/actionsel.
 * Include it after actionsel.sp, inside the plugin, where the
 * behaviours and the predicates are in scope.
 *
 * ActionSel_GetDesiredBotAction replaces the body of GetDesiredBotAction.
 * The RecoverDefenderFromDisconnectedSpawn call at the top of the shipped
 * function is not part of the decision and stays in the caller.
 */
#if !defined _actionsel_included
 #error Include actionsel.sp before this file.
#endif

#pragma semicolon 1
#pragma newdecls required

/* One predicate, asked once, only when the walk reaches it. */
static bool ActionSel_Ask(int client, int predicate)
{
	switch (predicate)
	{
		case ActionSel_PredMoneyToCollect:
		{
			return CTFBotCollectMoney_IsPossible(client);
		}
		case ActionSel_PredInUpgradeZone:
		{
			return TF2_IsInUpgradeZone(client);
		}
		case ActionSel_PredShoppedThisBreak:
		{
			return g_bShoppedThisBreak[client];
		}
		case ActionSel_PredMovingToFront:
		{
			return ActionsManager.LookupEntityActionByName(client, "DefenderMoveToFront") != INVALID_ACTION;
		}
		case ActionSel_PredUpgradesEnabled:
		{
			return redbots_manager_bot_use_upgrades.BoolValue;
		}
		case ActionSel_PredHasUpgraded:
		{
			return g_bHasUpgraded[client];
		}
		case ActionSel_PredUpgradeMidRound:
		{
			return ShouldUpgradeMidRound(client);
		}
		case ActionSel_PredHasSniperRifle:
		{
			return HasSniperRifle(client);
		}
		case ActionSel_PredSniperStalled:
		{
			return IsSniperStalled(client);
		}
		case ActionSel_PredAttackTargetFound:
		{
			return CTFBotDefenderAttack_SelectTarget(client);
		}
		case ActionSel_PredTankTargetFound:
		{
			return CTFBotAttackTank_SelectTarget(client);
		}
		case ActionSel_PredGiantToMark:
		{
			return CTFBotMarkGiant_IsPossible(client);
		}
		case ActionSel_PredNearbyMoney:
		{
			return CTFBotCollectNearMoney_SelectTarget(client);
		}
		case ActionSel_PredStickyTrapPossible:
		{
			return CTFBotStickyTrap_IsPossible(client);
		}
	}

	return false;
}

/* The walk. The bound is the predicate count, so it cannot spin. */
stock ActionSel_Action ActionSel_Walk(int client, ActionSel_RoundState state, ActionSel_Class botClass)
{
	int node = ActionSel_Root[view_as<int>(state)][view_as<int>(botClass)];

	for (int step = 0; step <= ActionSel_PredicateCount; step++)
	{
		if (ActionSel_NodePredicate[node] == -1)
			return view_as<ActionSel_Action>(ActionSel_NodeWhenTrue[node]);

		if (ActionSel_Ask(client, ActionSel_NodePredicate[node]))
			node = ActionSel_NodeWhenTrue[node];
		else
			node = ActionSel_NodeWhenFalse[node];
	}

	return ActionSel_ActionNone;
}

/* One outcome id, one call site of the function this replaces. The
 * reason strings are the shipped ones byte for byte: they reach the debug
 * output and the test-bed's telemetry, so renaming one is a change. */
stock Action ActionSel_Dispatch(int client, BehaviorAction action, ActionSel_Action outcome)
{
	switch (outcome)
	{
		case ActionSel_ActionCollectMoneyIsPossible:
		{
			return action.SuspendFor(CTFBotCollectMoney(), "Is possible");
		}
		case ActionSel_ActionGotoUpgradeBetweenRounds:
		{
			return action.SuspendFor(CTFBotGotoUpgrade(), "!IsInUpgradeZone && RoundState_BetweenRounds");
		}
		case ActionSel_ActionMoveToFrontSkipUpgrading:
		{
			SetPlayerReady(client, true);
			return action.SuspendFor(CTFBotMoveToFront(), "Skip upgrading");
		}
		case ActionSel_ActionMoveToFrontShoppingDone:
		{
			return action.SuspendFor(CTFBotMoveToFront(), "Shopping is done, so take up a position");
		}
		case ActionSel_ActionGotoUpgradeBuyNow:
		{
			g_iBuyUpgradesNumber[client] = 0;
			return action.SuspendFor(CTFBotGotoUpgrade(), "Buy upgrades now");
		}
		case ActionSel_ActionCollectMoneyCollecting:
		{
			return action.SuspendFor(CTFBotCollectMoney(), "Collecting money");
		}
		case ActionSel_ActionMarkGiant:
		{
			return action.SuspendFor(CTFBotMarkGiant(), "Marking giant");
		}
		case ActionSel_ActionAttackTankScout:
		{
			return action.SuspendFor(CTFBotAttackTank(), "Scout: Attacking tank");
		}
		case ActionSel_ActionDefenderAttackScout:
		{
			return action.SuspendFor(CTFBotDefenderAttack(), "Scout: Attacking robots");
		}
		case ActionSel_ActionDefenderAttackSniper:
		{
			return action.SuspendFor(CTFBotDefenderAttack(), "Sniper Attacking robots");
		}
		case ActionSel_ActionEngineerIdle:
		{
			return action.SuspendFor(CTFBotMvMEngineerIdle(), "Engineer Start building");
		}
		case ActionSel_ActionSpyLurk:
		{
			return action.SuspendFor(CTFBotSpyLurkMvM(), "Spy do be lurking");
		}
		case ActionSel_ActionDefenderAttackIsPossible:
		{
			return action.SuspendFor(CTFBotDefenderAttack(), "CTFBotAttack_IsPossible");
		}
		case ActionSel_ActionAttackTank:
		{
			return action.SuspendFor(CTFBotAttackTank(), "Attacking tank");
		}
		case ActionSel_ActionCollectNearMoney:
		{
			return action.SuspendFor(CTFBotCollectNearMoney(), "Nearby money");
		}
		case ActionSel_ActionStickyTrap:
		{
			return action.SuspendFor(CTFBotStickyTrap(), "Nothing to fight, so lay a trap");
		}
		case ActionSel_ActionGuardPoint:
		{
			return action.SuspendFor(CTFBotGuardPoint(), "Nothing to do, so hold the hatch");
		}
	}

	/* Every other outcome is the shipped Plugin_Continue:
	 * ActionSel_ActionNone: never returned; reaching it is a bug in the table
	 * ActionSel_ActionKeepWalkingToFront: DefenderMoveToFront is on the stack already
	 * ActionSel_ActionKeepOwnBreakBehaviour: the engineer's nest, the spy's lurk, the rifle sniper's perch
	 * ActionSel_ActionKeepSnipingPosition: Timer_PlayerSpawn gave him the sniping behaviour
	 * ActionSel_ActionKeepHealing: the medic starts healing on the game's own behaviour
	 * ActionSel_ActionKeepWaitingForClass: no class yet
	 * ActionSel_ActionWaitOutsideRound: the nine round states the choice never reads
	 * ActionSel_ActionStrandedAsShipped: mvm-vnn: the shipped chain leaves this bot standing, and the port does too
	 */
	return Plugin_Continue;
}

/* The whole of GetDesiredBotAction's decision. */
stock Action ActionSel_GetDesiredBotAction(int client, BehaviorAction action)
{
	ActionSel_RoundState state = view_as<ActionSel_RoundState>(GameRules_GetRoundState());
	ActionSel_Class botClass = view_as<ActionSel_Class>(TF2_GetPlayerClass(client));

	return ActionSel_Dispatch(client, action, ActionSel_Walk(client, state, botClass));
}
