/* Generated by internal/spgen. Do not edit.
 *
 * The decision in internal/actionsel, as data.
 *
 * The table is not a translation of the Go. It is extracted by running
 * actionsel.Select against a Facts that refuses a question it has not
 * been told about, answering each refused question both ways and
 * recurring, so the order the table asks in is the order the Go
 * evaluates in, short circuits included.
 *
 * Nothing here calls anything. The edge in actionsel_dispatch.sp answers
 * the predicates and maps an outcome back onto the action it hands the bot.
 */
#if defined _actionsel_included
 #endinput
#endif
#define _actionsel_included

#pragma semicolon 1
#pragma newdecls required

enum ActionSel_Class
{
	ActionSel_ClassUnknown = 0,
	ActionSel_ClassScout = 1,
	ActionSel_ClassSniper = 2,
	ActionSel_ClassSoldier = 3,
	ActionSel_ClassDemoMan = 4,
	ActionSel_ClassMedic = 5,
	ActionSel_ClassHeavy = 6,
	ActionSel_ClassPyro = 7,
	ActionSel_ClassSpy = 8,
	ActionSel_ClassEngineer = 9
};

enum ActionSel_Action
{
	ActionSel_ActionNone = 0,
	ActionSel_ActionCollectMoneyIsPossible = 1,
	ActionSel_ActionGotoUpgradeBetweenRounds = 2,
	ActionSel_ActionMoveToFrontSkipUpgrading = 3,
	ActionSel_ActionMoveToFrontShoppingDone = 4,
	ActionSel_ActionGotoUpgradeBuyNow = 5,
	ActionSel_ActionCollectMoneyCollecting = 6,
	ActionSel_ActionMarkGiant = 7,
	ActionSel_ActionAttackTankScout = 8,
	ActionSel_ActionDefenderAttackScout = 9,
	ActionSel_ActionDefenderAttackSniper = 10,
	ActionSel_ActionEngineerIdle = 11,
	ActionSel_ActionSpyLurk = 12,
	ActionSel_ActionDefenderAttackIsPossible = 13,
	ActionSel_ActionAttackTank = 14,
	ActionSel_ActionCollectNearMoney = 15,
	ActionSel_ActionStickyTrap = 16,
	ActionSel_ActionGuardPoint = 17,
	ActionSel_ActionKeepWalkingToFront = 18,
	ActionSel_ActionKeepOwnBreakBehaviour = 19,
	ActionSel_ActionKeepSnipingPosition = 20,
	ActionSel_ActionKeepHealing = 21,
	ActionSel_ActionKeepWaitingForClass = 22,
	ActionSel_ActionWaitOutsideRound = 23,
	ActionSel_ActionStrandedAsShipped = 24
};

enum ActionSel_RoundState
{
	ActionSel_RoundInit = 0,
	ActionSel_RoundPregame = 1,
	ActionSel_RoundStartGame = 2,
	ActionSel_RoundPreround = 3,
	ActionSel_RoundRunning = 4,
	ActionSel_RoundTeamWin = 5,
	ActionSel_RoundRestart = 6,
	ActionSel_RoundStalemate = 7,
	ActionSel_RoundGameOver = 8,
	ActionSel_RoundBonus = 9,
	ActionSel_RoundBetweenRounds = 10
};

/* The decision as data, so the edge can ask lazily
 *
 * Three of the predicates have side effects, so filling them all in
 * before deciding is not what the plugin does today. A node names one
 * predicate and the node to go to for each answer; the edge asks for a
 * predicate only when the walk reaches it, and never twice, because the
 * answer is what chose the next node.
 *
 * A node with ActionSel_NodePredicate of -1 answers: ActionSel_NodeWhenTrue
 * holds the outcome.
 */
#define ActionSel_PredicateCount 14

enum
{
	ActionSel_PredMoneyToCollect = 0,
	ActionSel_PredInUpgradeZone = 1,
	ActionSel_PredShoppedThisBreak = 2,
	ActionSel_PredMovingToFront = 3,
	ActionSel_PredUpgradesEnabled = 4,
	ActionSel_PredHasUpgraded = 5,
	ActionSel_PredUpgradeMidRound = 6,
	ActionSel_PredHasSniperRifle = 7,
	ActionSel_PredSniperStalled = 8,
	ActionSel_PredAttackTargetFound = 9,
	ActionSel_PredTankTargetFound = 10,
	ActionSel_PredGiantToMark = 11,
	ActionSel_PredNearbyMoney = 12,
	ActionSel_PredStickyTrapPossible = 13
};

#define ActionSel_NodeCount 93

int ActionSel_NodePredicate[ActionSel_NodeCount] = {
	-1, -1, -1, 1, 6, 5, 4, -1,
	-1, -1, -1, -1, 9, 10, 11, 0,
	1, 6, 5, 4, -1, -1, 8, 7,
	1, 6, 5, 4, -1, -1, -1, -1,
	12, 9, 10, 1, 6, 5, 4, -1,
	13, 9, 10, 1, 6, 5, 4, -1,
	1, 6, 5, 4, 10, 9, 1, 6,
	5, 4, -1, 1, 6, 5, 4, -1,
	1, 6, 5, 4, -1, -1, -1, 3,
	-1, -1, 4, 3, 2, 1, 0, -1,
	3, 8, 7, 8, 7, 3, 2, 1,
	0, 3, 2, 1, 0
};

int ActionSel_NodeWhenTrue[ActionSel_NodeCount] = {
	23, 22, 5, 1, 3, 4, 5, 6,
	7, 8, 9, 24, 10, 9, 8, 7,
	15, 16, 17, 18, 10, 20, 20, 22,
	23, 24, 25, 26, 14, 13, 15, 17,
	30, 29, 28, 34, 35, 36, 37, 16,
	39, 29, 28, 42, 43, 44, 45, 21,
	47, 48, 49, 50, 28, 29, 53, 54,
	55, 56, 12, 58, 59, 60, 61, 11,
	63, 64, 65, 66, 1, 18, 4, 69,
	2, 3, 72, 69, 71, 71, 68, 19,
	69, 71, 81, 69, 83, 84, 82, 82,
	68, 83, 81, 81, 68
};

int ActionSel_NodeWhenFalse[ActionSel_NodeCount] = {
	-1, -1, -1, 2, 1, 3, 1, -1,
	-1, -1, -1, -1, 11, 12, 13, 14,
	2, 15, 16, 15, -1, -1, 21, 20,
	2, 23, 24, 23, -1, -1, -1, -1,
	31, 32, 33, 2, 34, 35, 34, -1,
	32, 40, 41, 2, 42, 43, 42, -1,
	2, 47, 48, 47, 32, 52, 2, 53,
	54, 53, -1, 2, 58, 59, 58, -1,
	2, 63, 64, 63, -1, -1, -1, 70,
	-1, -1, 73, 74, 75, 76, 77, -1,
	79, 80, 71, 69, 69, 74, 85, 86,
	87, 74, 89, 90, 91
};

int ActionSel_Root[11][10] = {
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{6, 19, 27, 38, 46, 51, 57, 38, 62, 67},
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
	{78, 78, 88, 78, 78, 78, 78, 78, 92, 92}
};
