/*
Package body lists the Go packages that become SourcePawn bodies.

One list, read by cmd/gen and by the tests that prove the output, so a body
that is generated is a body that is checked. A package under this directory and
not in All is generated by nobody and proved by nobody.
*/
package body

import (
	"fmt"
	"path/filepath"

	"github.com/m-this/tf2-mvm-bots-go/internal/gosubset"
	"github.com/m-this/tf2-mvm-bots-go/internal/spaction"
	"github.com/m-this/tf2-mvm-bots-go/internal/spbody"
)

// ExternDir is the one package a body may import: the engine calls, each
// carrying the directive that says how SourcePawn writes it.
const ExternDir = "internal/engine"

// Body is one Go package and the file it becomes.
type Body struct {
	// Dir is the package, relative to the repository root.
	Dir string
	// Out is the generated file, relative to the output directory.
	Out string
	// Hooks is the generated DHook callbacks, relative to the output
	// directory. They are a file of their own because they name SourceMod's
	// DHookParam and MRESReturn, which the standalone SourcePawn the bodies
	// are proved under does not have.
	Hooks string
	// Prefix goes in front of every emitted name. Go_ says at the call site
	// that the function came from here and is not to be edited.
	Prefix string
}

// Actions are the behaviours: a Go package each, emitted as the BehaviorAction
// subclass the plugin includes. They are bodies with a shape around them, so
// they go through the same extern declarations and the same ownership rule.
var Actions = []Body{
	{Dir: "internal/action/spysap", Out: "sourcepawn/spysap.sp", Prefix: "Go_"},
}

// All is every body. Adding one here is what makes it generated.
var All = []Body{
	{Dir: "internal/body/roster", Out: "sourcepawn/roster.sp", Hooks: "sourcepawn/roster_dhooks.sp", Prefix: "Go_"},
	{Dir: "internal/body/scan", Out: "sourcepawn/scan.sp", Prefix: "Go_"},
}

// Generate emits every body, keyed by its output path.
func Generate(root string) (map[string][]byte, error) {
	return GenerateWith(root, "")
}

// GenerateWith is Generate with one extra SourcePawn name pretended to be
// generated, which is how the double-ownership refusal is tested without
// keeping a body around whose only job is to be refused.
func GenerateWith(root string, alsoOwned string) (map[string][]byte, error) {
	declared, err := spbody.ExternsFromDir(filepath.Join(root, ExternDir))
	if err != nil {
		return nil, err
	}
	out := make(map[string][]byte, len(All))
	owned := make(map[string]string)
	if alsoOwned != "" {
		owned[alsoOwned] = "a caller's test"
	}
	for _, b := range All {
		g, err := spbody.GenerateDir(filepath.Join(root, b.Dir), spbody.Config{
			Prefix:  b.Prefix,
			Externs: declared.Funcs,
			Tags:    declared.Tags,
		})
		if err != nil {
			return nil, fmt.Errorf("generating %s: %w", b.Dir, err)
		}
		for _, name := range g.Emitted {
			owned[name] = b.Dir
		}
		out[b.Out] = []byte(g.Source)
		if g.Hooks == "" {
			continue
		}
		if b.Hooks == "" {
			return nil, fmt.Errorf("%s declares a DHook and names no file to put it in", b.Dir)
		}
		out[b.Hooks] = []byte(g.Hooks)
	}
	for _, a := range Actions {
		source, err := spaction.Generate(filepath.Join(root, a.Dir), spbody.Config{
			Prefix:  a.Prefix,
			Externs: declared.Funcs,
			Tags:    declared.Tags,
		})
		if err != nil {
			return nil, fmt.Errorf("generating %s: %w", a.Dir, err)
		}
		out[a.Out] = []byte(source)
	}

	// A plugin extern names SourcePawn this repository has not written yet.
	// The day it does, the extern has to go: a function owned in both places
	// is the duplication the epic exists to remove, and nothing else would
	// notice, because both would compile.
	for qualified, x := range declared.Funcs {
		if x.Plugin {
			if dir, ported := owned[x.Func]; ported {
				return nil, fmt.Errorf("%s is declared as a plugin extern and %s generates %s; delete the extern and call it directly", qualified, dir, x.Func)
			}
			continue
		}
		// The other direction: a body extern says the port owns it, and
		// a name nothing generates is a claim that stopped being true.
		if x.Body {
			if _, ported := owned[x.Func]; !ported {
				return nil, fmt.Errorf("%s is declared as a body extern and nothing generates %s; make it a plugin extern, or port it", qualified, x.Func)
			}
		}
	}
	return out, nil
}

// SubsetConfig is what gosubset accepts in a body: the extern package, by the
// names it actually declares, and nothing else.
func SubsetConfig(root string) (gosubset.Config, error) {
	declared, err := spbody.ExternsFromDir(filepath.Join(root, ExternDir))
	if err != nil {
		return gosubset.Config{}, err
	}
	cfg := gosubset.DefaultConfig()
	names := make([]string, 0, len(declared.Funcs)+len(declared.Tags))
	for qualified := range declared.Funcs {
		names = append(names, qualified[len(externPackage)+1:])
	}
	for qualified := range declared.Tags {
		names = append(names, qualified[len(externPackage)+1:])
	}
	cfg.Packages[modulePath+"/"+ExternDir] = names
	return cfg, nil
}

const (
	modulePath    = "github.com/m-this/tf2-mvm-bots-go"
	externPackage = "engine"
)
