/*
Package body lists the Go packages that become SourcePawn bodies.

One list, read by cmd/gen and by the tests that prove the output, so a body
that is generated is a body that is checked. A package under this directory and
not in All is generated by nobody and proved by nobody.
*/
package body

import (
	"fmt"
	"maps"
	"path/filepath"
	"slices"

	"github.com/m-this/tf2-mvm-bots-go/internal/gosubset"
	"github.com/m-this/tf2-mvm-bots-go/internal/spaction"
	"github.com/m-this/tf2-mvm-bots-go/internal/spbody"
)

// ExternDir is the one package a body may import: the engine calls, each
// carrying the directive that says how SourcePawn writes it.
const ExternDir = "internal/engine"

// Body is one Go package and the file it becomes.
type Body struct {
	// Dir is the package, relative to the repository root.
	Dir string
	/*
		Out is the generated file, relative to the output directory.

		Empty means the package emits nothing, which is what a package
		of constants does: a caller folds a constant, so the value is
		written where it is used and there is no declaration to put
		anywhere. Such a package is in the list because being in the
		list is what makes it importable.
	*/
	Out string
	// Hooks is the generated DHook callbacks, relative to the output
	// directory. They are a file of their own because they name SourceMod's
	// DHookParam and MRESReturn, which the standalone SourcePawn the bodies
	// are proved under does not have.
	Hooks string
	// Prefix goes in front of every emitted name. Go_ says at the call site
	// that the function came from here and is not to be edited.
	Prefix string
}

// Actions are the behaviours: a Go package each, emitted as the BehaviorAction
// subclass the plugin includes. They are bodies with a shape around them, so
// they go through the same extern declarations and the same ownership rule.
var Actions = []Body{
	{
		Dir: "internal/action/spysap", Out: "sourcepawn/spysap.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/collectnearmoney", Out: "sourcepawn/collectnearmoney.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/destroyteleporter", Out: "sourcepawn/destroyteleporter.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/spysapplayer", Out: "sourcepawn/spysapplayer.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/attackforuber", Out: "sourcepawn/attackforuber.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/medicrevive", Out: "sourcepawn/medicrevive.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/campbomb", Out: "sourcepawn/campbomb.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/guardpoint", Out: "sourcepawn/guardpoint.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/evadebuster", Out: "sourcepawn/evadebuster.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/spylurk", Out: "sourcepawn/spylurk.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/markgiant", Out: "sourcepawn/markgiant.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/gotoupgrade", Out: "sourcepawn/gotoupgrade.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/upgrade", Out: "sourcepawn/upgrade.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/collectmoney", Out: "sourcepawn/collectmoney.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/stickytrap", Out: "sourcepawn/stickytrap.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/engineerbuilddisposable", Out: "sourcepawn/engineerbuilddisposable.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/attack", Out: "sourcepawn/attack.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/gethealth", Out: "sourcepawn/gethealth.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/movetofront", Out: "sourcepawn/movetofront.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/engineeridle", Out: "sourcepawn/engineeridle.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/engineerbuildteleporter", Out: "sourcepawn/engineerbuildteleporter.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/attacktank", Out: "sourcepawn/attacktank.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/engineerbuilddispenser", Out: "sourcepawn/engineerbuilddispenser.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/spycheck", Out: "sourcepawn/spycheck.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/getammo", Out: "sourcepawn/getammo.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/action/engineerbuildsentrygun", Out: "sourcepawn/engineerbuildsentrygun.sp", Prefix: "Go_",
	},
}

// All is every body. Adding one here is what makes it generated.
var All = []Body{
	// One constant, and no emitted file: SourcePawn needs no declaration
	// for a number every caller folds. It is in the list because being in
	// the list is what makes a package importable.
	{Dir: "internal/body/slots", Prefix: "Go_"},
	{Dir: "internal/body/roster", Out: "sourcepawn/roster.sp", Hooks: "sourcepawn/roster_dhooks.sp", Prefix: "Go_"},
	{Dir: "internal/body/scan", Out: "sourcepawn/scan.sp", Prefix: "Go_"},
	{Dir: "internal/body/medic", Out: "sourcepawn/medic.sp", Prefix: "Go_"},
	{
		Dir: "internal/body/shared", Out: "sourcepawn/shared.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/botcommands", Out: "sourcepawn/botcommands.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/statnatives", Out: "sourcepawn/statnatives.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/aimweapons", Out: "sourcepawn/aimweapons.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/panels", Out: "sourcepawn/panels.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/addmenu", Out: "sourcepawn/addmenu.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/prefmenu", Out: "sourcepawn/prefmenu.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/teammenu", Out: "sourcepawn/teammenu.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/manage", Out: "sourcepawn/manage.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/botnames", Out: "sourcepawn/botnames.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/mapconfig", Out: "sourcepawn/mapconfig.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/seating", Out: "sourcepawn/seating.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/upgradereport", Out: "sourcepawn/upgradereport.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/teamchange", Out: "sourcepawn/teamchange.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/composition", Out: "sourcepawn/composition.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/settings", Out: "sourcepawn/settings.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/lifecycle", Out: "sourcepawn/lifecycle.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/commands", Out: "sourcepawn/commands.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/readystate", Out: "sourcepawn/readystate.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/dumpspot", Out: "sourcepawn/dumpspot.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/soundhook", Out: "sourcepawn/soundhook.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/pluginstart", Out: "sourcepawn/pluginstart.sp", Prefix: "Go_",
	},
	/* Shipped, for the three records rather than for any function

	This package holds no function at all, but the enum structs it carries
	have methods, and compareMembers walks those against the shipped ones.
	Without the path they would generate and prove nothing. */
	{
		Dir: "internal/body/declarations", Out: "sourcepawn/declarations.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/pluginbot", Out: "sourcepawn/pluginbot.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/tfupgrades", Out: "sourcepawn/tf_upgrades.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/offsets", Out: "sourcepawn/offsets.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/sdkcalls", Out: "sourcepawn/sdkcalls.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/dhooks", Out: "sourcepawn/dhooks.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/humans", Out: "sourcepawn/humans.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/roster_counts", Out: "sourcepawn/roster_counts.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/botreset", Out: "sourcepawn/botreset.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/threataudit", Out: "sourcepawn/threataudit.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/hooks", Out: "sourcepawn/hooks.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/medicnudge", Out: "sourcepawn/medicnudge.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/dispatch", Out: "sourcepawn/dispatch.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/bottle", Out: "sourcepawn/bottle.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/scoutjump", Out: "sourcepawn/scoutjump.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/spawnexit", Out: "sourcepawn/spawnexit.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/mediccall", Out: "sourcepawn/mediccall.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/stuckwatch", Out: "sourcepawn/stuckwatch.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/pathing", Out: "sourcepawn/pathing.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/readiness", Out: "sourcepawn/readiness.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/botqueries", Out: "sourcepawn/botqueries.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/archipelago", Out: "sourcepawn/archipelago.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/gameevents", Out: "sourcepawn/gameevents.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/behaviourreset", Out: "sourcepawn/behaviourreset.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/playerpref", Out: "sourcepawn/playerpref.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/loadouts", Out: "sourcepawn/loadouts.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/cosmetics", Out: "sourcepawn/cosmetics.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/chat", Out: "sourcepawn/chat.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/econitem", Out: "sourcepawn/econitem.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/sapper", Out: "sourcepawn/sapper.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/spawnroute", Out: "sourcepawn/spawnroute.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/reflect", Out: "sourcepawn/reflect.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/movement", Out: "sourcepawn/movement.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/actionstack", Out: "sourcepawn/actionstack.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/angles", Out: "sourcepawn/angles.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/stocks", Out: "sourcepawn/stocks.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/bombinfo", Out: "sourcepawn/bombinfo.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/nestmove", Out: "sourcepawn/nestmove.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/buildarea", Out: "sourcepawn/buildarea.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/nesthint", Out: "sourcepawn/nesthint.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/nestpick", Out: "sourcepawn/nestpick.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/lineoffire", Out: "sourcepawn/lineoffire.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/nestscore", Out: "sourcepawn/nestscore.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/entity", Out: "sourcepawn/entity.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/loadout", Out: "sourcepawn/loadout.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/state", Out: "sourcepawn/state.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/mission", Out: "sourcepawn/mission.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/weapons", Out: "sourcepawn/weapons.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/finders", Out: "sourcepawn/finders.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/nestspot", Out: "sourcepawn/nestspot.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/buildings", Out: "sourcepawn/buildings.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/faults", Out: "sourcepawn/debug_faults.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/stickies", Out: "sourcepawn/demoman_stickies.sp", Prefix: "Go_",
	},
	/*
		No Shipped, and it had one: source/redbots3/blu_assist.sp at
		b48ad70, which the snapshot still holds.

		The link is cut because the lever is not that lever any more. The
		shipped one is the scale at one human on RED rising to 1.0 at six,
		and it refuses anything above 1.0; this one is a straight multiplier
		from 0.1 to 10.0, so a server can say the team finds the mission easy
		as well as hard. tf2-archipelago offers 10% to 1000% and the shipped
		convar silently clamped every value above 1.0 back to 1.0.

		The mechanism went with it. The shipped body wrote "max health
		additive bonus" and m_iMaxHealth on the frame after the spawn and the
		robots still came at the popfile's health: TF2 finishes building the
		robot after that frame, and recomputes the maximum from the
		attributes afterwards. What holds is answering SDKHook_GetMaxHealth,
		written a tenth of a second after the spawn.

		Every function the shipped file also holds changed, so what is left
		to compare would prove nothing. The comparison says exactly that
		rather than passing on six identical reasons in reshaped.
	*/
	{
		Dir: "internal/body/bluassist", Out: "sourcepawn/blu_assist.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/upgraderules", Out: "sourcepawn/upgrade_rules.sp", Prefix: "Go_",
	},
	{
		Dir: "internal/body/uber", Out: "sourcepawn/uber.sp", Prefix: "Go_",
	},
}

// Generate emits every body, keyed by its output path.
func Generate(root string) (map[string][]byte, error) {
	return GenerateWith(root, "")
}

// GenerateWith is Generate with one extra SourcePawn name pretended to be
// generated, which is how the double-ownership refusal is tested without
// keeping a body around whose only job is to be refused.
func GenerateWith(root string, alsoOwned string) (map[string][]byte, error) {
	declared, err := spbody.ExternsFromDir(filepath.Join(root, ExternDir))
	if err != nil {
		return nil, err
	}
	out := make(map[string][]byte, len(All))
	owned := make(map[string]owner)
	if alsoOwned != "" {
		owned[alsoOwned] = owner{Dir: "a caller's test"}
	}

	for _, name := range generatedElsewhere {
		owned[name] = owner{Dir: "a generator outside this list"}
	}
	table, err := importable(root)
	if err != nil {
		return nil, err
	}
	// One type check of internal/engine for the whole list rather than one
	// per body. It is 18000 lines and there are ninety of them.
	cache, err := spbody.NewCache(filepath.Join(root, ExternDir))
	if err != nil {
		return nil, err
	}
	for _, b := range All {
		externs, err := externsFor(root, b.Dir, declared.Funcs, table)
		if err != nil {
			return nil, err
		}
		g, err := spbody.GenerateDir(filepath.Join(root, b.Dir), spbody.Config{
			Prefix:  b.Prefix,
			Externs: externs,
			Tags:    declared.Tags,
			Cache:   cache,
		})
		if err != nil {
			return nil, fmt.Errorf("generating %s: %w", b.Dir, err)
		}
		for _, d := range g.Declares {
			owned[d.SP] = owner{Dir: b.Dir, Decl: d}
		}
		if b.Out != "" {
			out[b.Out] = []byte(g.Source)
		}
		if g.Hooks == "" {
			continue
		}
		if b.Hooks == "" {
			return nil, fmt.Errorf("%s declares a DHook and names no file to put it in", b.Dir)
		}
		out[b.Hooks] = []byte(g.Hooks)
	}
	for _, a := range Actions {
		externs, err := externsFor(root, a.Dir, declared.Funcs, table)
		if err != nil {
			return nil, err
		}
		source, declares, err := spaction.Generate(filepath.Join(root, a.Dir), spbody.Config{
			Prefix:  a.Prefix,
			Externs: externs,
			Tags:    declared.Tags,
			Cache:   cache,
		})
		if err != nil {
			return nil, fmt.Errorf("generating %s: %w", a.Dir, err)
		}
		for _, d := range declares {
			owned[d.SP] = owner{Dir: a.Dir, Decl: d}
		}
		out[a.Out] = []byte(source)
	}

	if err := checkExterns(root, declared, owned); err != nil {
		return nil, err
	}
	if err := CheckResets(root, declared, owned); err != nil {
		return nil, err
	}
	return out, nil
}

// owner is the package that generates one SourcePawn name, and the declaration
// it generates it from. The declaration is empty for a name nothing in this
// list translates: a constructor spaction writes itself, or a generator outside
// the list.
type owner struct {
	Dir  string
	Decl spbody.Declaration
}

/*
checkExterns holds every extern against what the port actually generates.

Two directions, and they fail differently.

A plugin extern names SourcePawn this repository has not written yet. The day it
does, the extern has to go: a function owned in both places is the duplication
the epic exists to remove, and nothing else would notice, because both would
compile.

A body extern says the opposite, that the port owns the name. That claim has two
halves and only the first was ever checked. A name nothing generates is a claim
that stopped being true. A name something generates with a different shape is
worse, because it survives the generator, survives spcomp -- int, float, every
tag and every handle are one cell -- and arrives as a bot doing the wrong thing
with an argument it read as the wrong type.
*/
func checkExterns(root string, declared spbody.Declared, owned map[string]owner) error {
	signatures, err := spbody.SignaturesFromDir(filepath.Join(root, ExternDir))
	if err != nil {
		return err
	}
	for _, qualified := range slices.Sorted(maps.Keys(declared.Funcs)) {
		x := declared.Funcs[qualified]
		if x.Plugin {
			if o, ported := owned[x.Func]; ported {
				return fmt.Errorf("%s is declared as a plugin extern and %s generates %s; delete the extern and call it directly", qualified, o.Dir, x.Func)
			}
			continue
		}
		if !x.Body {
			continue
		}
		o, ported := owned[x.Func]
		if !ported {
			return fmt.Errorf("%s is declared as a body extern and nothing generates %s; make it a plugin extern, or port it", qualified, x.Func)
		}
		if o.Decl.Sig == nil {
			// A constructor spaction writes, or a generator outside
			// the list. Neither has a Go signature to compare.
			continue
		}
		if x.Untyped {
			continue
		}
		here, checked := signatures[qualified]
		if !checked {
			return fmt.Errorf("%s is declared as a body extern and the extern package type checks no function of that name", qualified)
		}
		allowance := spbody.Allowance{Trail: len(x.Trail), Buffer: x.Sized || x.Fills || x.Into}
		if difference, same := spbody.SameShape(here, o.Decl.Sig, o.Decl.Optional, allowance); !same {
			return fmt.Errorf("%s is declared as a body extern for %s, which %s generates from %s, and they are different shapes: %s",
				qualified, x.Func, o.Dir, o.Decl.Go, difference)
		}
	}
	return nil
}

// SubsetConfig is what gosubset accepts in a body: the extern package and the
// other generated packages, each by the names it actually declares, and nothing
// else.
func SubsetConfig(root string) (gosubset.Config, error) {
	declared, err := spbody.ExternsFromDir(filepath.Join(root, ExternDir))
	if err != nil {
		return gosubset.Config{}, err
	}
	table, err := importable(root)
	if err != nil {
		return gosubset.Config{}, err
	}
	cfg := gosubset.DefaultConfig()
	for p, names := range subsetPackages(table) {
		cfg.Packages[p] = names
	}
	names := make([]string, 0, len(declared.Funcs)+len(declared.Tags))
	for qualified := range declared.Funcs {
		names = append(names, qualified[len(externPackage)+1:])
	}
	for qualified := range declared.Tags {
		names = append(names, qualified[len(externPackage)+1:])
	}
	cfg.Packages[modulePath+"/"+ExternDir] = names
	return cfg, nil
}

/*
generatedElsewhere are the functions this repository emits from generators that
are not in the list above: internal/tables and internal/threat.

Kept by hand because neither has a registry, so adding one here is part of
adding it there. A body extern naming one of these is as owned as one naming a
body's.
*/
var generatedElsewhere = []string{
	"GetTunedWeaponRanges",
	"AttributeID",
	"ThreatPriorityOf",
	"DemoPipeMaxRange",
	"UpgradeRankGeneral",
	"UpgradeRankClass",
	"UpgradeRankLoadout",
	"UpgradeRankEngineerMetal",
	"UnrankedUpgradePriority",
}

const (
	modulePath    = "github.com/m-this/tf2-mvm-bots-go"
	externPackage = "engine"
)
